# This is an example configuration for a TelegramGateway to be included in the complete emersyx config.toml file.
[[TelegramGateways]]
identifier = "example_telegram_id"
api_token = "Telegram Bot API token"
updates_limit = 100
updates_timeout = 60
updates_allowed = [
    "message",
    "edited_message",
    "channel_post",
    "edited_channel_post",
    "inline_query",
    "chosen_inline_result",
    "callback_query",
    "shipping_query",
    "pre_checkout_query"
]
plugin = "path/to/emtg.so"
