[[processors]]
plugin_path = "path/to/emi2t.so"
identifier = "emi2t"
config = "path/to/emi2t.toml"

[[processors]]
plugin_path = "path/to/emirc_voice.so"
identifier = "emirc_voice"
config = "path/to/emirc_voice.toml"

[[IRCGateways]]
plugin_path = "path/to/emirc.so"
identifier = "example_irc_id"
nick = "emersyx"
ident = "emersyx"
name = "emersyx"
version = "alpha"
server_address = "chat.freenode.net"
server_port = 6697
server_use_ssl = true
quit_message = "bye from emersyx!"

[[TelegramGateways]]
plugin_path = "path/to/emtg.so"
identifier = "example_telegram_id"
api_token = "Telegram Bot API token"
updates_limit = 100
updates_timeout = 60
updates_allowed = [
    "message",
    "edited_message",
    "channel_post",
    "edited_channel_post",
    "inline_query",
    "chosen_inline_result",
    "callback_query",
    "shipping_query",
    "pre_checkout_query"
]

[router]
plugin_path = "path/to/emrouter.so"

[[routes]]
source = "example_irc_id"
destination = [ "emi2t", "emirc_voice" ]

[[routes]]
source = "example_telegram_id"
destination = [ "emi2t" ]
