# This is an example configuration for an IRCGateway to be included in the complete emersyx config.toml file.
[[IRCGateways]]
identifier = "example_irc_id"
nick = "emersyx"
ident = "emersyx"
name = "emersyx"
version = "alpha"
server_address = "chat.freenode.net"
server_port = 6697
server_use_ssl = true
quit_message = "bye from emersyx!"
plugin = "path/to/emirc.so"
