log_stdout = true
log_level = 4

[[peripherals]]
identifier = "emirc"
config_path = "path/to/emirc.toml"
plugin_path = "path/to/emirc.so"

[[peripherals]]
identifier = "emtg"
config_path = "path/to/emtg.toml"
plugin_path = "path/to/emtg.so"

[[peripherals]]
identifier = "emi2t"
config_path = "path/to/emi2t.toml"
plugin_path = "path/to/emi2t.so"

[[routes]]
source = "emirc"
destinations = [ "emi2t" ]

[[routes]]
source = "emtg"
destinations = [ "emi2t" ]
